<!DOCTYPE html>
<html lang="en">
<head>
    <title>DIRGHAYU FITNESS FACTORY</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="{{url('/js/jquery-3.2.1.slim.min.js')}}"></script>
    <script src="{{url('/js/popper.min.js')}}"></script>
    <script src="{{url('/js/bootstrap.min.js')}}"></script>
</head>
<body>
<div class="col-sm-12">
<div align="center"><h5>DIRGHAYU FITNESS FACTORY INVOICE</h5></div>
    <div class="row">
        <div class="col-sm-3 offset-sm-9">
            <h5><b>Invoice #0{{$invoice['id']}}</b></h5>
        </div>
    </div>
    <hr>
    <div class="row" style="margin-bottom:-50px;">
        <div class="col-sm-4">
            <h5>Bill To</h5>
            <div>{{$invoice['billto']['first_name']}} {{$invoice['billto']['last_name']}}</div>
        </div>
        <div class="col-sm-4 offset-sm-4">
            <h5>Customer Email</h5>
            <div>{{$invoice['billto']['email']}}</div>
        </div>
        <div class="col-sm-4 offset-sm-8">
            <h5>Customer Phone</h5>
            <div>{{$invoice['billto']['phone']}}</div>
        </div>
    </div>
    <div class="row" style="margin-bottom:-10px;">
        <div class="col-sm-4">
            <h5>Customer Address</h5>
            <div>{{$invoice['billto']['address']}}</div>
        </div>
        <div class="col-sm-4 offset-sm-4">
            <h5>Invoice Date</h5>
            <div>{{$invoice['invoice_date']}}</div>
        </div>
    </div>
    
    <table class="table" width="100%" align="center">
            <tr>
                <th>Name</th>
                <th>Quantity</th>
                <th>Rate</th>
                <th>Amount</th>
            </tr>
            @foreach($invoice['invoiceitems'] as $item)
            <tr>
                <td>{{ $item->name }}</td>
                <td>{{ $item->quantity }}</td>
                <td>{{ $item->rate }}</td>
                <td>{{ $item->amount }}</td>
            </tr>
            @endforeach
    </table>
    <div class="row justify-content-end">
        <div class="col-md-2" style="text-align:right;margin-right:35px;">
            <div><h6><b>Subtotal </b>: {{$invoice['subtotal']}}</h6></div>
            <div><h6><b>Discount </b>: {{$invoice['discount']}}</h6></div>
            <div><h6><b>Tax </b>: {{$invoice['tax']}}</h6></div>
            <div><h6><b>Total </b>: {{$invoice['total']}}</h6></div>
            <div class="mb-5"><h6><b>Generated By </b>: {{$invoice['user']['first_name']}} {{$invoice['user']['last_name']}}</h6></div>
        </div>
    </div>
</div>
</body>
</html>