<!DOCTYPE html>
<html lang="en">
<head>
    <title>Gym App</title>
    <style type="text/css">
        body{
            /*font-size: 7px;
            padding-left: 80px;
            padding-right: 80px;*/
        }
        table {
            border-collapse: collapse;
        }

        table, th, td {
            border: 1px solid black;
            padding-left: 8px;
            padding-top: 2px;
            padding-bottom: 2px;
        }
        .top-border {
            border-top: none;
            padding-top: -3px !important; 
        }
	</style>
</head>
<body>
<div align="center">
    <div align="center" style="margin-bottom:20px;">GYM INVOICE</div>
    <table width="100%" align="center" class="top-border">
        <tr>
            <td>Invoice Number : </td>
            <td>#0{{$invoice['id']}}</td>
        </tr>
        <tr>
            <td>Customer Name : </td>
            <td>{{$invoice['billto']['first_name']}} {{$invoice['billto']['last_name']}}</td>
        </tr>
        <tr>
            <td>Customer Email : </td>
            <td>{{$invoice['billto']['email']}}</td>
        </tr>
        <tr>
            <td>Customer Phone : </td>
            <td>{{$invoice['billto']['phone']}}</td>
        </tr>
        <tr>
            <td>Invoice Date : </td>
            <td>{{$invoice['invoice_date']}}</td>
        </tr>
        <tr>
            <td>Customer Address : </td>
            <td>{{$invoice['billto']['address']}}</td>
        </tr>
    </table>
    <table width="100%" align="center" class="top-border">
    <tr><td colspan="4" align="center">INVOICE ITEMS</td></tr>
        <tr>
            <td>Name</td>
            <td>Quantity</td>
            <td>Rate</td>
            <td>Amount</td>
        </tr>
        @foreach($invoice['invoiceitems'] as $item)
        <tr>
            <td>{{ $item->name }}</td>
            <td>{{ $item->quantity }}</td>
            <td>{{ $item->rate }}</td>
            <td>{{ $item->amount }}</td>
        </tr>
        @endforeach
        <tr>
            <td colspan='2'></td>
            <td>Subtotal : </td>
            <td>{{$invoice['subtotal']}}</td>
        </tr>
        <tr>
            <td colspan='2'></td>
            <td>Discount : </td>
            <td>{{$invoice['discount']}}</td>
        </tr>
        <tr>
            <td colspan='2'></td>
            <td>Tax : </td>
            <td>{{$invoice['tax']}}</td>
        </tr>
        <tr>
            <td colspan='2'></td>
            <td>Total : </td>
            <td>{{$invoice['total']}}</td>
        </tr>
        <tr>
            <td colspan='2'></td>
            <td>Generated By : </td>
            <td>{{$invoice['user']['first_name']}} {{$invoice['user']['last_name']}}</td>
        </tr>
    </table> 
</div>

</body>
</html>