<template>
	<VueDatatable ref="vueDatatable" v-can:view__invoice :columns="columns" :url="url" @gaction="onAction">
		<th>Invoice #</th>
		<th>Client</th>
		<th>Date</th>
		<th>Total</th>
		<th>Generated By</th>
		<th v-show="$can('view__invoice') || $can('delete__invoice')">Action</th>
    </VueDatatable>
</template>
<script>
import axios from 'axios';
import VueDatatable from '@components/custom/VueDatatable.vue';
import moment from 'moment';

export default {
	name: 'NoticeTable',
	components: {
		VueDatatable
	},
	data() {
		return {
			columns: [
		        {data:'id', name:'id', width:"80px"},
		        {data:function(data){
                    return data.billto.first_name+' '+data.billto.last_name;
                }, name:'bill_to'},
                {data:(data) => {
					return moment(data.invoice_date).format("DD-MM-YYYY");
				}, name:'invoice_date', width:"70px"},
                {data:(data) => {
					return data.total+' '+this.$store.getters['init/currency'];
				}, name:'total', width:"50px"},
		        {data:function(data){
                    return data.user.first_name+' '+data.user.last_name;
                }, name:'user_id'},
		        {data:(data) => {
					let actions = "";
					if(this.$can('view__invoice')) {
						actions += "<button class='btn btn-outline-info-new' data-g-action='view' data-g-actiondata="+data.id+"><i class='fas fa-eye'></i> <span class='button-text'>View</span></button>";
					}
					if(this.$can('delete__invoice')) {
						actions += " <button class='btn btn-outline-danger-new' data-g-action='delete' data-g-actiondata="+data.id+"><i class='fas fa-trash-alt'></i> <span class='button-text'>Delete</span></button>";
					}
					return actions;
	          	}, name:'action', width:"140px"}
		    ],
		    url: '/api/v1/invoice/list',
		}
	},
	mounted() {
		if(this.$route.params.message){
			this.$snotify.success(null, this.$route.params.message);
		}
	},
	methods: {
		async onAction(action) {
			if(action.action === 'view') {
				this.$router.push('/view-invoice/'+action.data)
			}
			if(action.action === 'delete'){
				try {
					const res = await axios.post('/api/v1/invoice/delete' , { id: action.data });
					this.$refs.vueDatatable.draw();
					this.$snotify.success(null, res.data.message);
				}
				catch(err) {
					this.$snotify.error(null, err.message);
				}
			}
		}
	}
}
</script>