<template>
	<VueDatatable :columns="columns" :url="url" @gaction="onAction">
		<th>Id</th>
		<th>Client</th>
		<th>Date</th>
		<th>Total</th>
		<th>Generated By</th>
		<th>Action</th>
    </VueDatatable>
</template>
<script>
import axios from 'axios';
import VueDatatable from '@components/custom/VueDatatable.vue';

export default {
	name: 'NoticeTable',
	components: {
		VueDatatable
	},
	data() {
		return {
			columns: [
		        {data:'id', name:'id'},
		        {data:function(data){
                    return data.billto.first_name+' '+data.billto.last_name;
                }, name:'bill_to'},
                {data:'invoice_date', name:'invoice_date'},
                {data:'total', name:'total'},
		        {data:function(data){
                    return data.user.first_name+' '+data.user.last_name;
                }, name:'user_id'},
		        {data:function(data){
	            	return "<button class='btn btn-primary' data-g-action='view' data-g-actiondata="+data.id+">Update</button> <button class='btn btn-danger' data-g-action='delete' data-g-actiondata="+data.id+">Delete</button>";
	          	}, name:'action'}
		    ],
		    url: '/api/v1/invoice/list',
		}
	},
	methods: {
		
		async onAction(action) {
			if(action.action === 'view') {
				this.$router.push('/update-invoice/'+action.data)
				//console.log(action.data);
			}
			if(action.action === 'delete'){
				try{
					let invoiceId = action.data
					let res = await axios.post('/api/v1/invoice/delete' , { id: invoiceId }, { headers: {"Authorization" : this.$store.getters['auth/authHeaders'].Authorization} });
					this.$snotify.success(null, res.data.message);
				}
				catch(err){
					this.$snotify.error(null, err.message);

				}
			}
		}
	}

}
</script>