<template>
	<DashboardPage v-can:view__invoice>
		<div class="app-main__inner">
		<div class="app-page-title">
	    	<div class="page-title-wrapper">
	            <div class="page-title-heading">
	                <div class="page-title-icon">
	                    <i class="pe-7s-display1 icon-gradient bg-premium-dark text-danger">
	                    </i>
	                </div>
	                <div>GENERATE INVOICE</div>wqe
	            </div>    
	        </div>
	    </div>            
	    <div v-if="invoice.billto" class="main-card mb-3 card">
	        <div class="card-body col-sm-12">
                <h5 class="card-title"></h5>
                <div class="row mb-4">
                    <div class="col-sm-2 offset-sm-10">
                        <div class="position-relative form-group">
                            <h5 style="text-align:right;margin-right:35px;"><b>Invoice #{{invoice.id}}</b></h5>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row mb-4">
                    <div class="col-sm-4">
                        <div class="position-relative form-group">
                            <h5>Bill To</h5>
                            <div>{{invoice.billto.first_name}} {{invoice.billto.last_name}}</div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="position-relative form-group">
                            <h5>Customer Email</h5>
                            <div>{{invoice.customer_email}}</div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="position-relative form-group">
                            <h5>Customer Phone</h5>
                            <div>{{invoice.customer_phone}}</div>
                        </div>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-4">
                        <div class="position-relative form-group">
                            <h5>Customer Address</h5>
                            <div>{{invoice.customer_address}}</div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="position-relative form-group">
                            <h5>Invoice Date</h5>
                            <div>{{invoice.invoice_date}}</div>
                        </div>
                    </div>
                </div>
                <table align="center" width="100%" class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Quantity</th>
                            <th>Rate</th>
                            <th>Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="(invoiceItem, index) in invoice.invoiceitems" :key="index">
                            <td>{{invoiceItem.name}}</td>
                            <td>{{invoiceItem.quantity}}</td>
                            <td>{{invoiceItem.rate}}</td>
                            <td>{{invoiceItem.amount}}</td>
                        </tr>
                    </tbody>
                </table>
                <hr>
                <div class="row justify-content-end">
                    <div class="col-md-2" style="text-align:right;margin-right:35px;">
                        <div><h6><b>Subtotal </b>: {{invoice.subtotal}}</h6></div>
                        <div><h6><b>Discount </b>: {{invoice.discount}}</h6></div>
                        <div><h6><b>Tax </b>: {{invoice.tax}}</h6></div>
                        <div><h6><b>Total </b>: {{invoice.total}}</h6></div>
                        <div class="mb-5"><h6><b>Generated By </b>: {{invoice.user.first_name}} {{invoice.user.last_name}}</h6></div>

                        <button class="btn btn-lg btn-info" type="button" @click="downloadPdf(invoice.id)">Download</button>
                        <!-- <button class="btn btn-lg btn-alternate" type="button">Email</button> -->
                    </div>
	            </div>
	        </div>
	    </div>
	</div>
	</DashboardPage>
</template>
<script>
import axios from 'axios';
import DashboardPage from '@layouts/DashboardPage';
import downloadjs from 'downloadjs';

export default {
	name: 'AddInvoice',
	components: {
		DashboardPage
	},
	data() {
		return {
			invoice:{
				bill_to: null,
                customer_email: null,
                customer_address: null,
                customer_phone: null,
                invoice_date: null,
                subtotal: 0,
                discount: 0,
                tax: 0,
                total: 0,
				user_id: null,
				invoiceitems:[
					{
						name: null,
						quantity: 0,
						rate: 0,
						amount: 0,
					},
				],
			},
			staffs: null,
			customers: null,
		}
	},
	async mounted() {
		try {
			if(this.$route.params.id != null) {
				this.getInvoiceList();
		    }			
            this.getCustomerList();
            await this.getStaffMemberList();
		} catch (err) {
			this.$snotify.error(null, err.message);
		}
    },
    methods: {
        async getInvoiceList() {
            const res      = await axios.get('/api/v1/invoice/list/'+this.$route.params.id)
            this.invoice = res.data.data
        },
        async getCustomerList() {
            const customerRes = await axios.get('/api/v1/customer/list')
            this.customers = customerRes.data.data
        },
        async getStaffMemberList() {
            const staffRes = await axios.post('/api/v1/staff/member/list' , null)
            this.staffs = staffRes.data.data
        },
        async downloadPdf(id) {
           
            const response = await axios({
                url: '/api/v1/invoice/download/'+id,
                method: 'GET',
                responseType: 'blob', // important
                headers: {"Authorization" : this.$store.getters['auth/authHeaders'].Authorization},
            });

            downloadjs(response.data, 'invoice.pdf', 'application/pdf');
        }
    }
}
</script>